/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ServiceRouteRouteImport } from './routes/service/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceIndexRouteImport } from './routes/service/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServiceTopRouteImport } from './routes/service/top'
import { Route as ServiceSolvesRouteImport } from './routes/service/solves'
import { Route as ServiceInstancesRouteImport } from './routes/service/instances'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminInstancesRouteImport } from './routes/admin/instances'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminChallengesRouteImport } from './routes/admin/challenges'
import { Route as ServiceEventsIndexRouteImport } from './routes/service/events/index'
import { Route as ServiceChallengesIndexRouteImport } from './routes/service/challenges/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as ServiceEventsIdRouteRouteImport } from './routes/service/events/$id/route'
import { Route as ServiceChallengesIdRouteRouteImport } from './routes/service/challenges/$id/route'
import { Route as AdminEventsIdRouteRouteImport } from './routes/admin/events/$id/route'
import { Route as ServiceEventsIdIndexRouteImport } from './routes/service/events/$id/index'
import { Route as ServiceChallengesIdIndexRouteImport } from './routes/service/challenges/$id/index'
import { Route as AdminEventsIdIndexRouteImport } from './routes/admin/events/$id/index'
import { Route as ServiceEventsIdTrendRouteImport } from './routes/service/events/$id/trend'
import { Route as ServiceEventsIdScoreboardRouteImport } from './routes/service/events/$id/scoreboard'
import { Route as ServiceEventsIdInstancesRouteImport } from './routes/service/events/$id/instances'
import { Route as ServiceEventsIdChallengesRouteImport } from './routes/service/events/$id/challenges'
import { Route as AdminEventsIdWriteupsRouteImport } from './routes/admin/events/$id/writeups'
import { Route as AdminEventsIdUsersRouteImport } from './routes/admin/events/$id/users'
import { Route as AdminEventsIdData_presentRouteImport } from './routes/admin/events/$id/data_present'
import { Route as AdminEventsIdAnnouncementsRouteImport } from './routes/admin/events/$id/announcements'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRouteRoute = ServiceRouteRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceIndexRoute = ServiceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ServiceTopRoute = ServiceTopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => ServiceRouteRoute,
} as any)
const ServiceSolvesRoute = ServiceSolvesRouteImport.update({
  id: '/solves',
  path: '/solves',
  getParentRoute: () => ServiceRouteRoute,
} as any)
const ServiceInstancesRoute = ServiceInstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => ServiceRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInstancesRoute = AdminInstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChallengesRoute = AdminChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ServiceEventsIndexRoute = ServiceEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => ServiceRouteRoute,
} as any)
const ServiceChallengesIndexRoute = ServiceChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => ServiceRouteRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ServiceEventsIdRouteRoute = ServiceEventsIdRouteRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => ServiceRouteRoute,
} as any)
const ServiceChallengesIdRouteRoute =
  ServiceChallengesIdRouteRouteImport.update({
    id: '/challenges/$id',
    path: '/challenges/$id',
    getParentRoute: () => ServiceRouteRoute,
  } as any)
const AdminEventsIdRouteRoute = AdminEventsIdRouteRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ServiceEventsIdIndexRoute = ServiceEventsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceEventsIdRouteRoute,
} as any)
const ServiceChallengesIdIndexRoute =
  ServiceChallengesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServiceChallengesIdRouteRoute,
  } as any)
const AdminEventsIdIndexRoute = AdminEventsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEventsIdRouteRoute,
} as any)
const ServiceEventsIdTrendRoute = ServiceEventsIdTrendRouteImport.update({
  id: '/trend',
  path: '/trend',
  getParentRoute: () => ServiceEventsIdRouteRoute,
} as any)
const ServiceEventsIdScoreboardRoute =
  ServiceEventsIdScoreboardRouteImport.update({
    id: '/scoreboard',
    path: '/scoreboard',
    getParentRoute: () => ServiceEventsIdRouteRoute,
  } as any)
const ServiceEventsIdInstancesRoute =
  ServiceEventsIdInstancesRouteImport.update({
    id: '/instances',
    path: '/instances',
    getParentRoute: () => ServiceEventsIdRouteRoute,
  } as any)
const ServiceEventsIdChallengesRoute =
  ServiceEventsIdChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => ServiceEventsIdRouteRoute,
  } as any)
const AdminEventsIdWriteupsRoute = AdminEventsIdWriteupsRouteImport.update({
  id: '/writeups',
  path: '/writeups',
  getParentRoute: () => AdminEventsIdRouteRoute,
} as any)
const AdminEventsIdUsersRoute = AdminEventsIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminEventsIdRouteRoute,
} as any)
const AdminEventsIdData_presentRoute =
  AdminEventsIdData_presentRouteImport.update({
    id: '/data_present',
    path: '/data_present',
    getParentRoute: () => AdminEventsIdRouteRoute,
  } as any)
const AdminEventsIdAnnouncementsRoute =
  AdminEventsIdAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AdminEventsIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/service': typeof ServiceRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/instances': typeof AdminInstancesRoute
  '/admin/users': typeof AdminUsersRoute
  '/service/instances': typeof ServiceInstancesRoute
  '/service/solves': typeof ServiceSolvesRoute
  '/service/top': typeof ServiceTopRoute
  '/admin/': typeof AdminIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/admin/events/$id': typeof AdminEventsIdRouteRouteWithChildren
  '/service/challenges/$id': typeof ServiceChallengesIdRouteRouteWithChildren
  '/service/events/$id': typeof ServiceEventsIdRouteRouteWithChildren
  '/admin/events': typeof AdminEventsIndexRoute
  '/service/challenges': typeof ServiceChallengesIndexRoute
  '/service/events': typeof ServiceEventsIndexRoute
  '/admin/events/$id/announcements': typeof AdminEventsIdAnnouncementsRoute
  '/admin/events/$id/data_present': typeof AdminEventsIdData_presentRoute
  '/admin/events/$id/users': typeof AdminEventsIdUsersRoute
  '/admin/events/$id/writeups': typeof AdminEventsIdWriteupsRoute
  '/service/events/$id/challenges': typeof ServiceEventsIdChallengesRoute
  '/service/events/$id/instances': typeof ServiceEventsIdInstancesRoute
  '/service/events/$id/scoreboard': typeof ServiceEventsIdScoreboardRoute
  '/service/events/$id/trend': typeof ServiceEventsIdTrendRoute
  '/admin/events/$id/': typeof AdminEventsIdIndexRoute
  '/service/challenges/$id/': typeof ServiceChallengesIdIndexRoute
  '/service/events/$id/': typeof ServiceEventsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/instances': typeof AdminInstancesRoute
  '/admin/users': typeof AdminUsersRoute
  '/service/instances': typeof ServiceInstancesRoute
  '/service/solves': typeof ServiceSolvesRoute
  '/service/top': typeof ServiceTopRoute
  '/admin': typeof AdminIndexRoute
  '/service': typeof ServiceIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/service/challenges': typeof ServiceChallengesIndexRoute
  '/service/events': typeof ServiceEventsIndexRoute
  '/admin/events/$id/announcements': typeof AdminEventsIdAnnouncementsRoute
  '/admin/events/$id/data_present': typeof AdminEventsIdData_presentRoute
  '/admin/events/$id/users': typeof AdminEventsIdUsersRoute
  '/admin/events/$id/writeups': typeof AdminEventsIdWriteupsRoute
  '/service/events/$id/challenges': typeof ServiceEventsIdChallengesRoute
  '/service/events/$id/instances': typeof ServiceEventsIdInstancesRoute
  '/service/events/$id/scoreboard': typeof ServiceEventsIdScoreboardRoute
  '/service/events/$id/trend': typeof ServiceEventsIdTrendRoute
  '/admin/events/$id': typeof AdminEventsIdIndexRoute
  '/service/challenges/$id': typeof ServiceChallengesIdIndexRoute
  '/service/events/$id': typeof ServiceEventsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/service': typeof ServiceRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/instances': typeof AdminInstancesRoute
  '/admin/users': typeof AdminUsersRoute
  '/service/instances': typeof ServiceInstancesRoute
  '/service/solves': typeof ServiceSolvesRoute
  '/service/top': typeof ServiceTopRoute
  '/admin/': typeof AdminIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/admin/events/$id': typeof AdminEventsIdRouteRouteWithChildren
  '/service/challenges/$id': typeof ServiceChallengesIdRouteRouteWithChildren
  '/service/events/$id': typeof ServiceEventsIdRouteRouteWithChildren
  '/admin/events/': typeof AdminEventsIndexRoute
  '/service/challenges/': typeof ServiceChallengesIndexRoute
  '/service/events/': typeof ServiceEventsIndexRoute
  '/admin/events/$id/announcements': typeof AdminEventsIdAnnouncementsRoute
  '/admin/events/$id/data_present': typeof AdminEventsIdData_presentRoute
  '/admin/events/$id/users': typeof AdminEventsIdUsersRoute
  '/admin/events/$id/writeups': typeof AdminEventsIdWriteupsRoute
  '/service/events/$id/challenges': typeof ServiceEventsIdChallengesRoute
  '/service/events/$id/instances': typeof ServiceEventsIdInstancesRoute
  '/service/events/$id/scoreboard': typeof ServiceEventsIdScoreboardRoute
  '/service/events/$id/trend': typeof ServiceEventsIdTrendRoute
  '/admin/events/$id/': typeof AdminEventsIdIndexRoute
  '/service/challenges/$id/': typeof ServiceChallengesIdIndexRoute
  '/service/events/$id/': typeof ServiceEventsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/service'
    | '/register'
    | '/admin/challenges'
    | '/admin/dashboard'
    | '/admin/instances'
    | '/admin/users'
    | '/service/instances'
    | '/service/solves'
    | '/service/top'
    | '/admin/'
    | '/service/'
    | '/admin/events/$id'
    | '/service/challenges/$id'
    | '/service/events/$id'
    | '/admin/events'
    | '/service/challenges'
    | '/service/events'
    | '/admin/events/$id/announcements'
    | '/admin/events/$id/data_present'
    | '/admin/events/$id/users'
    | '/admin/events/$id/writeups'
    | '/service/events/$id/challenges'
    | '/service/events/$id/instances'
    | '/service/events/$id/scoreboard'
    | '/service/events/$id/trend'
    | '/admin/events/$id/'
    | '/service/challenges/$id/'
    | '/service/events/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/admin/challenges'
    | '/admin/dashboard'
    | '/admin/instances'
    | '/admin/users'
    | '/service/instances'
    | '/service/solves'
    | '/service/top'
    | '/admin'
    | '/service'
    | '/admin/events'
    | '/service/challenges'
    | '/service/events'
    | '/admin/events/$id/announcements'
    | '/admin/events/$id/data_present'
    | '/admin/events/$id/users'
    | '/admin/events/$id/writeups'
    | '/service/events/$id/challenges'
    | '/service/events/$id/instances'
    | '/service/events/$id/scoreboard'
    | '/service/events/$id/trend'
    | '/admin/events/$id'
    | '/service/challenges/$id'
    | '/service/events/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/service'
    | '/register'
    | '/admin/challenges'
    | '/admin/dashboard'
    | '/admin/instances'
    | '/admin/users'
    | '/service/instances'
    | '/service/solves'
    | '/service/top'
    | '/admin/'
    | '/service/'
    | '/admin/events/$id'
    | '/service/challenges/$id'
    | '/service/events/$id'
    | '/admin/events/'
    | '/service/challenges/'
    | '/service/events/'
    | '/admin/events/$id/announcements'
    | '/admin/events/$id/data_present'
    | '/admin/events/$id/users'
    | '/admin/events/$id/writeups'
    | '/service/events/$id/challenges'
    | '/service/events/$id/instances'
    | '/service/events/$id/scoreboard'
    | '/service/events/$id/trend'
    | '/admin/events/$id/'
    | '/service/challenges/$id/'
    | '/service/events/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ServiceRouteRoute: typeof ServiceRouteRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/': {
      id: '/service/'
      path: '/'
      fullPath: '/service/'
      preLoaderRoute: typeof ServiceIndexRouteImport
      parentRoute: typeof ServiceRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/service/top': {
      id: '/service/top'
      path: '/top'
      fullPath: '/service/top'
      preLoaderRoute: typeof ServiceTopRouteImport
      parentRoute: typeof ServiceRouteRoute
    }
    '/service/solves': {
      id: '/service/solves'
      path: '/solves'
      fullPath: '/service/solves'
      preLoaderRoute: typeof ServiceSolvesRouteImport
      parentRoute: typeof ServiceRouteRoute
    }
    '/service/instances': {
      id: '/service/instances'
      path: '/instances'
      fullPath: '/service/instances'
      preLoaderRoute: typeof ServiceInstancesRouteImport
      parentRoute: typeof ServiceRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/instances': {
      id: '/admin/instances'
      path: '/instances'
      fullPath: '/admin/instances'
      preLoaderRoute: typeof AdminInstancesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/challenges': {
      id: '/admin/challenges'
      path: '/challenges'
      fullPath: '/admin/challenges'
      preLoaderRoute: typeof AdminChallengesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/service/events/': {
      id: '/service/events/'
      path: '/events'
      fullPath: '/service/events'
      preLoaderRoute: typeof ServiceEventsIndexRouteImport
      parentRoute: typeof ServiceRouteRoute
    }
    '/service/challenges/': {
      id: '/service/challenges/'
      path: '/challenges'
      fullPath: '/service/challenges'
      preLoaderRoute: typeof ServiceChallengesIndexRouteImport
      parentRoute: typeof ServiceRouteRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/service/events/$id': {
      id: '/service/events/$id'
      path: '/events/$id'
      fullPath: '/service/events/$id'
      preLoaderRoute: typeof ServiceEventsIdRouteRouteImport
      parentRoute: typeof ServiceRouteRoute
    }
    '/service/challenges/$id': {
      id: '/service/challenges/$id'
      path: '/challenges/$id'
      fullPath: '/service/challenges/$id'
      preLoaderRoute: typeof ServiceChallengesIdRouteRouteImport
      parentRoute: typeof ServiceRouteRoute
    }
    '/admin/events/$id': {
      id: '/admin/events/$id'
      path: '/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/service/events/$id/': {
      id: '/service/events/$id/'
      path: '/'
      fullPath: '/service/events/$id/'
      preLoaderRoute: typeof ServiceEventsIdIndexRouteImport
      parentRoute: typeof ServiceEventsIdRouteRoute
    }
    '/service/challenges/$id/': {
      id: '/service/challenges/$id/'
      path: '/'
      fullPath: '/service/challenges/$id/'
      preLoaderRoute: typeof ServiceChallengesIdIndexRouteImport
      parentRoute: typeof ServiceChallengesIdRouteRoute
    }
    '/admin/events/$id/': {
      id: '/admin/events/$id/'
      path: '/'
      fullPath: '/admin/events/$id/'
      preLoaderRoute: typeof AdminEventsIdIndexRouteImport
      parentRoute: typeof AdminEventsIdRouteRoute
    }
    '/service/events/$id/trend': {
      id: '/service/events/$id/trend'
      path: '/trend'
      fullPath: '/service/events/$id/trend'
      preLoaderRoute: typeof ServiceEventsIdTrendRouteImport
      parentRoute: typeof ServiceEventsIdRouteRoute
    }
    '/service/events/$id/scoreboard': {
      id: '/service/events/$id/scoreboard'
      path: '/scoreboard'
      fullPath: '/service/events/$id/scoreboard'
      preLoaderRoute: typeof ServiceEventsIdScoreboardRouteImport
      parentRoute: typeof ServiceEventsIdRouteRoute
    }
    '/service/events/$id/instances': {
      id: '/service/events/$id/instances'
      path: '/instances'
      fullPath: '/service/events/$id/instances'
      preLoaderRoute: typeof ServiceEventsIdInstancesRouteImport
      parentRoute: typeof ServiceEventsIdRouteRoute
    }
    '/service/events/$id/challenges': {
      id: '/service/events/$id/challenges'
      path: '/challenges'
      fullPath: '/service/events/$id/challenges'
      preLoaderRoute: typeof ServiceEventsIdChallengesRouteImport
      parentRoute: typeof ServiceEventsIdRouteRoute
    }
    '/admin/events/$id/writeups': {
      id: '/admin/events/$id/writeups'
      path: '/writeups'
      fullPath: '/admin/events/$id/writeups'
      preLoaderRoute: typeof AdminEventsIdWriteupsRouteImport
      parentRoute: typeof AdminEventsIdRouteRoute
    }
    '/admin/events/$id/users': {
      id: '/admin/events/$id/users'
      path: '/users'
      fullPath: '/admin/events/$id/users'
      preLoaderRoute: typeof AdminEventsIdUsersRouteImport
      parentRoute: typeof AdminEventsIdRouteRoute
    }
    '/admin/events/$id/data_present': {
      id: '/admin/events/$id/data_present'
      path: '/data_present'
      fullPath: '/admin/events/$id/data_present'
      preLoaderRoute: typeof AdminEventsIdData_presentRouteImport
      parentRoute: typeof AdminEventsIdRouteRoute
    }
    '/admin/events/$id/announcements': {
      id: '/admin/events/$id/announcements'
      path: '/announcements'
      fullPath: '/admin/events/$id/announcements'
      preLoaderRoute: typeof AdminEventsIdAnnouncementsRouteImport
      parentRoute: typeof AdminEventsIdRouteRoute
    }
  }
}

interface AdminEventsIdRouteRouteChildren {
  AdminEventsIdAnnouncementsRoute: typeof AdminEventsIdAnnouncementsRoute
  AdminEventsIdData_presentRoute: typeof AdminEventsIdData_presentRoute
  AdminEventsIdUsersRoute: typeof AdminEventsIdUsersRoute
  AdminEventsIdWriteupsRoute: typeof AdminEventsIdWriteupsRoute
  AdminEventsIdIndexRoute: typeof AdminEventsIdIndexRoute
}

const AdminEventsIdRouteRouteChildren: AdminEventsIdRouteRouteChildren = {
  AdminEventsIdAnnouncementsRoute: AdminEventsIdAnnouncementsRoute,
  AdminEventsIdData_presentRoute: AdminEventsIdData_presentRoute,
  AdminEventsIdUsersRoute: AdminEventsIdUsersRoute,
  AdminEventsIdWriteupsRoute: AdminEventsIdWriteupsRoute,
  AdminEventsIdIndexRoute: AdminEventsIdIndexRoute,
}

const AdminEventsIdRouteRouteWithChildren =
  AdminEventsIdRouteRoute._addFileChildren(AdminEventsIdRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminChallengesRoute: typeof AdminChallengesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInstancesRoute: typeof AdminInstancesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventsIdRouteRoute: typeof AdminEventsIdRouteRouteWithChildren
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminChallengesRoute: AdminChallengesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInstancesRoute: AdminInstancesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEventsIdRouteRoute: AdminEventsIdRouteRouteWithChildren,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ServiceChallengesIdRouteRouteChildren {
  ServiceChallengesIdIndexRoute: typeof ServiceChallengesIdIndexRoute
}

const ServiceChallengesIdRouteRouteChildren: ServiceChallengesIdRouteRouteChildren =
  {
    ServiceChallengesIdIndexRoute: ServiceChallengesIdIndexRoute,
  }

const ServiceChallengesIdRouteRouteWithChildren =
  ServiceChallengesIdRouteRoute._addFileChildren(
    ServiceChallengesIdRouteRouteChildren,
  )

interface ServiceEventsIdRouteRouteChildren {
  ServiceEventsIdChallengesRoute: typeof ServiceEventsIdChallengesRoute
  ServiceEventsIdInstancesRoute: typeof ServiceEventsIdInstancesRoute
  ServiceEventsIdScoreboardRoute: typeof ServiceEventsIdScoreboardRoute
  ServiceEventsIdTrendRoute: typeof ServiceEventsIdTrendRoute
  ServiceEventsIdIndexRoute: typeof ServiceEventsIdIndexRoute
}

const ServiceEventsIdRouteRouteChildren: ServiceEventsIdRouteRouteChildren = {
  ServiceEventsIdChallengesRoute: ServiceEventsIdChallengesRoute,
  ServiceEventsIdInstancesRoute: ServiceEventsIdInstancesRoute,
  ServiceEventsIdScoreboardRoute: ServiceEventsIdScoreboardRoute,
  ServiceEventsIdTrendRoute: ServiceEventsIdTrendRoute,
  ServiceEventsIdIndexRoute: ServiceEventsIdIndexRoute,
}

const ServiceEventsIdRouteRouteWithChildren =
  ServiceEventsIdRouteRoute._addFileChildren(ServiceEventsIdRouteRouteChildren)

interface ServiceRouteRouteChildren {
  ServiceInstancesRoute: typeof ServiceInstancesRoute
  ServiceSolvesRoute: typeof ServiceSolvesRoute
  ServiceTopRoute: typeof ServiceTopRoute
  ServiceIndexRoute: typeof ServiceIndexRoute
  ServiceChallengesIdRouteRoute: typeof ServiceChallengesIdRouteRouteWithChildren
  ServiceEventsIdRouteRoute: typeof ServiceEventsIdRouteRouteWithChildren
  ServiceChallengesIndexRoute: typeof ServiceChallengesIndexRoute
  ServiceEventsIndexRoute: typeof ServiceEventsIndexRoute
}

const ServiceRouteRouteChildren: ServiceRouteRouteChildren = {
  ServiceInstancesRoute: ServiceInstancesRoute,
  ServiceSolvesRoute: ServiceSolvesRoute,
  ServiceTopRoute: ServiceTopRoute,
  ServiceIndexRoute: ServiceIndexRoute,
  ServiceChallengesIdRouteRoute: ServiceChallengesIdRouteRouteWithChildren,
  ServiceEventsIdRouteRoute: ServiceEventsIdRouteRouteWithChildren,
  ServiceChallengesIndexRoute: ServiceChallengesIndexRoute,
  ServiceEventsIndexRoute: ServiceEventsIndexRoute,
}

const ServiceRouteRouteWithChildren = ServiceRouteRoute._addFileChildren(
  ServiceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ServiceRouteRoute: ServiceRouteRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
